// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vojkmgadmyzlidobauli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvamttZ2FkbXl6bGlkb2JhdWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjE1OTcsImV4cCI6MjA2NDEzNzU5N30.T5rQvIgekM8z8fpWg8e38L919Gplp5kBrw_CgARA_1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);